name: Build Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name:  Checkout repo
      uses: actions/checkout@v3

    - name:  Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name:  Install Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name:  Build Docker Image
      run: docker build -t urlshortener-app .

    - name:  Done
      run: echo "Build successful!"
